# Author:  David Rigert
# Created: 5/22/2016
# CS372 Project 2: ftserve makefile

CXX = g++
CXXFLAGS = -std=c++11
SOURCE = ftserve.cpp

all: $(SOURCE)
	$(CXX) $(CXXFLAGS) $(SOURCE) -o ftserve

clean:
	$(RM) -f ftserve
